
DROP TABLE IF EXISTS CLIENTE;

CREATE TABLE CLIENTE (
  EMAIL VARCHAR(255) NOT NULL,
  NOMBRE VARCHAR(255) NOT NULL,
  APELLIDOS VARCHAR(255) NOT NULL,
  TELEFONO VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  PRIMARY KEY (EMAIL)
);

DROP TABLE IF EXISTS VIAJE;

CREATE TABLE VIAJE (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(255) NOT NULL,
    DESC_CORTA VARCHAR(255) NOT NULL,
	IMAGEN VARCHAR(255) NOT NULL,
	PRECIO INT NOT NULL,
	DESCUENTO INT,
	ASIA BOOLEAN,
	EUROPA BOOLEAN,
	AMERICA BOOLEAN,
	AFRICA BOOLEAN,
	OCEANIA BOOLEAN,
	DESC_LARGA VARCHAR(1048576),
	AGENCIA VARCHAR(9),
	PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS FAVORITOS;

CREATE TABLE FAVORITOS (
  ID INT(11) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID,EMAIL)
);

DROP TABLE IF EXISTS RESERVA;

CREATE TABLE RESERVA (
  ID_RESERVA INT(11) NOT NULL AUTO_INCREMENT,
  ID_VIAJE INT(11) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  NUMERO_PERSONAS INT(11) NOT NULL,
  FECHA_INICIO VARCHAR(255) NOT NULL,
  FECHA_FINAL VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID_VIAJE)
);

DROP TABLE IF EXISTS AGENCIA;

CREATE TABLE AGENCIA (
  EMAIL VARCHAR(255) NOT NULL,
  NOMBRE VARCHAR(255) NOT NULL,
  NIF VARCHAR(9) NOT NULL,
  TELEFONO VARCHAR(255) NOT NULL,
  PRIMARY KEY (NIF)
);
